using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Xml.Linq;
using EPubLibrary.Content.Guide;
using XHTMLClassLibrary.BaseElements;
using XHTMLClassLibrary.BaseElements.BlockElements;

namespace EPubLibrary.XHTML_Items
{
    internal class AboutPageFile : BaseXHTMLFile
    {
        public AboutPageFile()
        {
            DocumentType = GuideTypeEnum.CopyrightPage;
            pageTitle = "About";
            Div page = new Div();
            page.Class.Value = "about";
            H1 heading = new H1();
            heading.Add(new SimpleEPubText{ Text = "About"});
            page.Add(heading);

            Paragraph p1 = new Paragraph();

            Assembly asm = Assembly.GetEntryAssembly();
            string version = "???";
            if (asm != null)
            {
                version = asm.GetName().Version.ToString();
            }

            SimpleEPubText text1 = new SimpleEPubText();
            text1.Text = string.Format("This book was generated by Lord KiRon's FB2EPUB converter version {0}.", version);

            p1.Add(text1);
            page.Add(p1);

            Paragraph p2 = new Paragraph();

            SimpleEPubText text2 = new SimpleEPubText();
            text2.Text = string.Format("Эта книга создана при помощи конвертера FB2EPUB версии {0} написанного Lord KiRon ", version);

            p2.Add(text2);
            page.Add(p2);

            bodyElement.Add(page);
        }

    }
}
